#!/bin/bash

apt-get update

apt-get install -y \
  anacron \
  apt-transport-https \
  build-essential \
  ca-certificates \
  chromium \
  curl \
  flatpak \
  fonts-noto \
  gettext \
  git \
  gnupg \
  graphviz \
  grc \
  httpie \
  jq \
  libbz2-dev \
  libffi-dev \
  liblzma-dev \
  libncursesw5-dev \
  libnss3-tools \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  libxml2-dev \
  libxmlsec1-dev \
  llvm \
  lsb-release \
  mycli \
  make \
  nano \
  openjdk-11-jdk \
  pwgen \
  siege \
  software-properties-common \
  tk-dev \
  tmux \
  unzip \
  uuid-runtime \
  wget \
  xz-utils \
  zlib1g-dev \
  zip
