#!/bin/bash
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

if [[ ! -e /etc/apt/sources.list.d/docker.list ]]
then
    echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

    apt-get update
fi

apt-get install -y docker-ce
groupadd -f docker
usermod -aG docker $SUDO_USER
