#!/bin/bash
# configure CloudFoundry debian repo
if [[ -z "$(apt-key export cf-cli-eng@pivotal.io)" ]]
then 
  wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
fi

if [[ ! -e /etc/apt/sources.list.d/cloudfoundry-cli.list ]]
then
  echo "deb http://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
fi

apt-get update

apt-get install -y \
  cf-cli
