#!/bin/bash
# configure Conda debian repo
curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | apt-key add -

if [[ ! -e /etc/apt/sources.list.d/conda.list ]]
then
  echo "deb https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" | tee /etc/apt/sources.list.d/conda.list
fi

apt-get update

apt-get install -y \
  conda
