#!/bin/bash
if [[ ! -e /etc/apt/sources.list.d/backports.list ]]
then
    echo "deb http://ftp.debian.org/debian stretch-backports main" | tee /etc/apt/sources.list.d/backports.list

    apt-get update
fi

apt-get install -y \
  tilix
