#!/bin/bash

[[ -d $HOME/.bash-it ]] && echo "bash-it already installed." && exit 0

pushd $HOME
    git clone https://github.com/Bash-it/bash-it.git ~/.bash-it

    $HOME/.bash-it/install.sh --silent

    source $HOME/.bashrc

    bash-it enable completion git
    bash-it enable plugin ssh
    bash-it enable completion ssh
popd
