#!/bin/bash
SOURCE_CONDA='source $HOME/miniconda3/bin/activate'

wget -O /tmp/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash /tmp/miniconda.sh -b -f

source $HOME/miniconda3/bin/activate
conda init
