#!/bin/bash
mkdir -p ~/.local/share/fonts

http --follow https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip > /tmp/FiraCode.zip
unzip -d ~/.local/share/fonts /tmp/FiraCode.zip "*.ttf"

fc-cache -f
