#!/bin/bash

function install-deps {
  sudo apt-get update && sudo apt-get --no-install-recommends -yqq install \
    bash-completion \
    build-essential \
    cmake \
    libcurl3  \
    libcurl3-openssl-dev  \
    libssl1.0 \
    libssl1.0-dev \
    libxml2 \
    libxml2-dev  \
    pkg-config \
    ca-certificates \
    xclip 
}

if which lpass; then
  exit 0
fi

DIR=$(mktemp -d)

pushd $DIR
  install-deps
  git clone https://github.com/lastpass/lastpass-cli.git
  pushd lastpass-cli
    make
    sudo make install
  popd
popd