#!/bin/bash
DIR="$( cd "$( dirname $(readlink -f "${BASH_SOURCE[0]}") )" && pwd )"

DEFAULT_PROFILE=$(gsettings get com.gexperts.Tilix.ProfilesList default)
if [ "$DEFAULT_PROFILE" == "" ]; then
    DEFAULT_PROFILE="'$(uuidgen)'"
    gsettings set com.gexperts.Tilix.ProfilesList default "$DEFAULT_PROFILE"
    gsettings set com.gexperts.Tilix.ProfilesList list "[$DEFAULT_PROFILE]"
fi

export PROFILE_UUID=$(echo "$DEFAULT_PROFILE" | sed "s/'//g")
cat $DIR/tilix.dconf | envsubst |  dconf load /com/gexperts/Tilix/
